<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ISIPL-PUNV-L384" name="testcases.ProdSanityTest" tests="23" failures="3" timestamp="2022-10-11T12:11:59 IST" time="369.687" errors="0">
  <testcase name="prodSanityTest" time="18.422" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="18.193" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="25.763" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="19.251" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="14.900" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="19.909" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="16.382" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="13.894" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="15.702" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="18.471" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="20.690" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="9.384" classname="testcases.ProdSanityTest">
    <failure type="java.lang.AssertionError" message="expected [Disfruta+por-] but found [Privacy error]">
      <![CDATA[java.lang.AssertionError: expected [Disfruta+por-] but found [Privacy error]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcases.ProdSanityTest.prodSanityTest(ProdSanityTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- prodSanityTest -->
  <system-out/>
  <testcase name="prodSanityTest" time="16.865" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="14.818" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="9.907" classname="testcases.ProdSanityTest">
    <failure type="java.lang.AssertionError" message="expected [BPACA] but found [Privacy error]">
      <![CDATA[java.lang.AssertionError: expected [BPACA] but found [Privacy error]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcases.ProdSanityTest.prodSanityTest(ProdSanityTest.java:19)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- prodSanityTest -->
  <system-out/>
  <testcase name="prodSanityTest" time="16.721" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="10.395" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="14.998" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="15.561" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="13.438" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="9.969" classname="testcases.ProdSanityTest">
    <failure type="java.lang.AssertionError" message="expected [Home - MyCreditTracker] but found [Privacy error]">
      <![CDATA[java.lang.AssertionError: expected [Home - MyCreditTracker] but found [Privacy error]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcases.ProdSanityTest.prodSanityTest(ProdSanityTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- prodSanityTest -->
  <system-out/>
  <testcase name="prodSanityTest" time="18.213" classname="testcases.ProdSanityTest"/>
  <system-out/>
  <testcase name="prodSanityTest" time="17.841" classname="testcases.ProdSanityTest"/>
  <system-out/>
</testsuite> <!-- testcases.ProdSanityTest -->
